### ISSUE TITLE
Ensure subscriber can detect and re-download updated granules based on collection redeliveries

### ISSUE THREAD

**Issue by carygeo** [podaac/data-subscriber#18]
Update CMR query to use `updated_since` rather than `created_at` in the CMR query:
```
    params = {
        'scroll': "true",
        'page_size': 2000,
        'sort_key': "-start_date",
        'provider': 'POCLOUD',
        'ShortName': short_name,
        'created_at': data_within_last_timestamp,
        'token': token,
        'bounding_box': bounding_extent,
    }
```
https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#c-updated-since

here:
https://github.com/podaac/data-subscriber/blob/main/subscriber/podaac_data_subscriber.py#L298

as well as here:
https://github.com/podaac/data-subscriber/blob/main/subscriber/podaac_data_subscriber.py#L310

**Comment by mgangl** [comment]
The only real issue with this change would be:

1. A user consistently using the subscriber and used the original data will not be able to "reproduce" that result since the underlying data has changed.
2. A user only needs "NRT" data and doesn't care if that data is updated later on. In this instance, they will downlaod data they don't need.

2 is one we can work on and add an additional (that's a lot of words starting with 'A') parameter **in future work** to specify updated_at vs created_at. I don't think that's in scope for this change, to be honest, and we should only add it if we get requests to do so.

1 is an issue with the data provider replacing these files. If it's simple replacement/metadata then this is fine. but there are times when a provider will send a "quicklook" file and then a better version days later, but uses the same filename and replaces the existing data.

**tl,dr;**
Go ahead with the fix and we'll respond to user requests to add a flag if desired to differentiate updated vs created times.

**Comment by carygeo** [comment]
Good points.  I can definitely see a future flag for static downloads vs continuous updating being useful to certain users.

I will move forward with this change for the time being.
