### ISSUE TITLE
display the total number of found granules

### ISSUE THREAD

**Issue by jinbow** [podaac/data-subscriber#33]
It will be helpful to display the total number of found granules, especially when the warning "Warning: only the most recent 2000 granules will be downloaded;" is shown.

**Comment by mike-gangl** [comment]
that information is displayed using the --verbose option:

`
 podaac-data-subscriber -c VIIRS_N20-OSPO-L2P-v2.61 -d test/ --verbose --start-date 2021-11-15T20:00:00Z
WARN: No .update in the data directory. (Is this the first run?)
Temporal Range: 2021-11-15T20:00:00Z,2021-11-16T16:35:18Z
Provider: POCLOUD
Updated Since: 2021-11-15T20:00:00Z
https://cmr.earthdata.nasa.gov/search/granules.umm_json?scroll=true&page_size=2000&sort_key=-start_date&provider=POCLOUD&updated_since=2021-11-15T20%3A00%3A00Z&ShortName=VIIRS_N20-OSPO-L2P-v2.61&temporal=2021-11-15T20%3A00%3A00Z%2C2021-11-16T16%3A35%3A18Z&token=51D3A0E8-ADB4-F26B-BB63-C26BD597691E&bounding_box=-180%2C-90%2C180%2C90
8 new granules found for VIIRS_N20-OSPO-L2P-v2.61 since 2021-11-15T20:00:00Z
Found 8 total files to download
Downloading files with extensions: ['.nc', '.h5', '.zip']
`

**8 new granules found for VIIRS_N20-OSPO-L2P-v2.61 since 2021-11-15T20:00:00Z
Found 8 total files to download**

**Comment by jinbow** [comment]
Got it. Thx. Does it make sense to have it on as default?

**Comment by mike-gangl** [comment]
Probably :) I'll make that update.
