### ISSUE TITLE
`machine` name in `.netrc`

### ISSUE THREAD

**Issue by sanAkel** [podaac/data-subscriber#69]
`.netrc` in following examples lists two different _names_ for `machine`. What should it be? Or, are they the same?

- [**Step 2**](https://github.com/podaac/data-subscriber#step-2-setup-your-earthdata-login) lists as: `machine urs.earthdata.nasa.gov`
- [Notebook](https://github.com/podaac/tutorials/blob/master/notebooks/l2-regridding/reprojection%20notebook.ipynb) has `uat.` added as in: `machine uat.urs.earthdata.nasa.gov`

Thanks!

**Comment by mike-gangl** [comment]
Thanks for your issue! you will more than likely use `machine urs.earthdata.nasa.gov`.

The `machine uat.urs.earthdata.nasa.gov` entry is for non-operational products and products in our 'test' environment. We originally wrote tutorials against ht eUAT environment because we were in the middle of our transition to the cloud and wanted to build out tutorials that worked. Now that much of PO.DAAC data is in our production cloud instance, we should go back and update those to non-UAT environments.

**Comment by mike-gangl** [comment]
i've added this as an issue in the tutorials repo (https://github.com/podaac/tutorials/issues/45) so i'll close this out in favor of fixing it there.
